### ISSUE TITLE
Flaky ClickHouseMonitor E2E test

### ISSUE THREAD

**Issue by dreamtalen** [antrea-io/theia#158]
Saw a kind e2e test failure at ClickHouseMonitor:
```
=== RUN   TestFlowVisibility/IPv4/ClickHouseMonitor
I0130 20:07:47.602139   21006 flowvisibility_test.go:629] Generating flow records to exceed monitor threshold...
I0130 20:08:05.824923   21006 flowvisibility_test.go:634] Waiting for the flows to be exported...
I0130 20:08:35.960261   21006 flowvisibility_test.go:641] Waiting for the monitor to detect and clean up the ClickHouse storage
    flowvisibility_test.go:678: 
        	Error Trace:	flowvisibility_test.go:678
        	            				flowvisibility_test.go:643
        	            				flowvisibility_test.go:519
        	Error:      	Max difference between 17877 and 9189.5 allowed is 2681.5499999999997, but difference was 8687.5
        	Test:       	TestFlowVisibility/IPv4/ClickHouseMonitor
        	Messages:   	Difference between expected and actual number of deleted Records should be lower than 15%
```

https://github.com/antrea-io/theia/actions/runs/4047547236/jobs/6961777226

**Comment by dreamtalen** [comment]
@yanjunz97 Could you help take a look?

**Comment by yanjunz97** [comment]
It seems this failure is caused by the ClickHouse monitor did not clean enough data as expected. We set 2 minutes for the ClickHouse to do the space rebalancing and the monitor to detect the space usage exceeding threshold. It is usually enough for tests. I guess some latency in ClickHouse server causes the delay. But I'm not able to reproduce this error locally and I do not find other cases on github CI for this failure. Maybe we can keep as it is for now and increase the time period if this error shows up more.

**Comment by dreamtalen** [comment]
> It seems this failure is caused by the ClickHouse monitor did not clean enough data as expected. We set 2 minutes for the ClickHouse to do the space rebalancing and the monitor to detect the space usage exceeding threshold. It is usually enough for tests. I guess some latency in ClickHouse server causes the delay. But I'm not able to reproduce this error locally and I do not find other cases on github CI for this failure. Maybe we can keep as it is for now and increase the time period if this error shows up more frequently.

Sounds good to me, thanks!
