### ISSUE TITLE
Update `hack/generate-manifest.sh --mode antrea-e2e`

### ISSUE THREAD

**Issue by heanlan** [antrea-io/theia#321]
`hack/generate-manifest.sh --mode antrea-e2e` is used to generates [YAML manifest](https://github.com/antrea-io/antrea/blob/main/build/yamls/flow-visibility-e2e.yml) for e2e tests in Antrea repository, which should only includes a ClickHouse server with default credentials. We need the script to create the YAML manifest because it is easier to keep the ClickHouse data schema in both Theia and Antrea in-sync.

The current script is a bit out-of-date, since we added new features to the Theia, by running the command will give us a manifest with a lot of more resources other than the required ClickHouse server. We would like to remove all the unnecessary resources from the generated script, including theia-manager, zookeeper, theia-cli. We would also like to replace `projects.registry.vmware.com/antrea/theia-clickhouse-server` by `projects.registry.vmware.com/antrea/clickhouse-server` in the generated manifest, as the Antrea e2e test does not need to be run based on theia built images.

**Comment by heanlan** [comment]
The issue was firstly raised by @yanjunz97 in https://github.com/antrea-io/antrea/pull/5020#discussion_r1213516534. Please feel free to correct me if I made anything wrong in the issue description.

**Comment by yanjunz97** [comment]
Thanks @heanlan for creating the issue! I would like to discuss a little bit more regarding ZooKeeper. As current data schema has dependency on ZooKeeper, e.g. we use replicated engine for tables, removing ZooKeeper in the generated YAML file might be a little bit difficult. But we still have some options:

- Add some new parameters in the helm chart values file and replace the ZooKeeper related contents by what we have before introducing ZooKeeper when `e2e` is enabled. But this option might not be meaningful to expose to users.
```
e2e:
  enable: false
```
- Instead of modifying in Helm chart, we can replace the ZooKeeper related text in `hack/generate-manifest.sh` to make sure the yaml file for antrea-e2e is still as expected.

I personally prefer the second one if we can make sure that implementation in shell script is readable.

**Comment by yuntanghsu** [comment]
@yanjunz97 @heanlan 
I had removed the flow-visibility-e2e.yaml and we created a helm charts under antrea/e2e/test  in this PR
https://github.com/antrea-io/antrea/pull/5171
Do we still want to update --mode antrea-e2e for Antrea? Or we can close this issue?

**Comment by yanjunz97** [comment]
Thanks YunTang for pointing out this. I think its good to close this issue. Let me close it
